[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
